[package]
name = "abhyas"
version = "0.1.0"
edition = "2021"
authors = ["Harshal Jadhav <bestt1315@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0"
rusqlite = { version = "0.30.0", features = ["bundled"] }
